### ISSUE TITLE
[MC1.16.2] WorldEdit Version 

### ISSUE THREAD

**Issue by Robertpuggle** [EngineHub/WorldEdit#1488]
Can the makers of the mod go to 1.16.2 visions

**Comment by octylFractal** [comment]
1) Use the template
2) We're already on 1.16.2.

**Comment by Robertpuggle** [comment]
It's not on curseforge

**Comment by octylFractal** [comment]
Cool, doesn't change that we've done it. Use a dev build if you want the latest changes immediately, with the caveat that it may break or corrupt your world.

**Comment by paddotk** [comment]
I'd suggest adding some indication of versioning, because this is totally unclear. I can't see any version info here, on the website nor the download page. I just downloaded the Forge version, I have Forge 1.16.1, but when I
After having downloaded the mod, I do see that the file is named `worldedit-forge-mc1.12.2-6.1.10-dist` so I guess it's for MC 1.12. But where are later versions available?

**Comment by wizjany** [comment]
![](https://i.imgur.com/x0Qum1p.png)
seems like pretty clear indication to me

**Comment by octylFractal** [comment]
I'm not sure how we could be any clearer with the file name. The later versions are all on CurseForge. Check the files tab.

**Comment by paddotk** [comment]
@wizjany @octylFractal Ok thanks, but anything above MC 1.12.2 is 'beta'. Doesn't this insinuate unstable/experimental versions?
That said, I seem to have overlooked the files tab 🤦 :p

**Comment by me4502** [comment]
Everything above 1.12.2 is not in beta. The only versions that are marked as beta are the 1.16 versions
