### ISSUE TITLE
/info command from other plugin is block in TAB-Complet when WorldEdit is used

### ISSUE THREAD

**Issue by CloudeLecaw** [EngineHub/WorldEdit#1568]
https://github.com/Zrips/CMI/issues/4400

Related to this thread where the plugin CMI usses the alias /info we noticed /info is not tabcompleted
with a bit of testing i found out that worldedit is blocking it from Tabcomplet
So is there an option to nopt block /info without geing everyone the permission from worldedit? :3

**Comment by octylFractal** [comment]
1) Use the template next time please.
2) WorldEdit is probably overriding the command as a whole, the end user needs to manually unregister the WorldEdit one using commands.yml, or Spigot/Paper needs to learn to pick commands per-player.

This isn't something we can particularly fix on our side, we've been using /info for ages but due to conflicts like this and Essentials, we're removing it in the future for /tool info. However, this won't occur for at least a few months, so one of the workarounds above should be used.

**Comment by CloudeLecaw** [comment]
hmm wen unsing /info the right command is executed from th plugin CMI

**Comment by octylFractal** [comment]
Likely because Spigot/Paper tracks both commands, realized that one couldn't execute, and skipped to the one that could. Nothing we control.

**Comment by CloudeLecaw** [comment]
I will lead that to the CMI github where this issue was reported first

Thank you for helping point it out :)
