### ISSUE TITLE
Incompatibility with biome type `CUSTOM`

### ISSUE THREAD

**Issue by NotMyFault** [EngineHub/WorldEdit#1856]
### WorldEdit Version

7.2.6-SNAPSHOT+5894-2e45a20

### Platform Version

git-Paper-137 (MC: 1.17.1)

### Bug Description

If you attempt to `//setbiome custom`, following exception occurs: https://gist.github.com/NotMyFault/617ecd61b136066dfb30a5641c99f216

### Expected Behavior

No exception/proper handling? I didn't take a look yet where `CUSTOM` is injected from, but I could imagine some spigot shenanigans for datapacks. But those biome shouldn't be considered at all, especially when same exception can be obtained if you are actually using datapacks with biome enhancements.

### Reproduction Steps

1. Create a cuboid selection
2. `//setbiome custom`

**Comment by wizjany** [comment]
This is basically expected behavior. Until WE-bukkit switches to using NMS for biomes, we have no choice but to assume spigot wouldn't lie to us in terrible ways. But it does, so `CUSTOM` is a perfectly valid biome type as reported by the API, and the server throwing errors is its problem, not ours.

#1538
