### ISSUE TITLE
Add support for relative (~) coordinates for //pos

### ISSUE THREAD

**Issue by Josh-65** [EngineHub/WorldEdit#2077]
### The Problem

World edit doesnt follow the standard coodiante of allowing "~ ~ ~" which is annoying for me when I do a lot of changes where the axe doesnt work (having to use F3 to enter the coordinates and convert then or use setblock and building to the correct position)

### A Solution

Change the syntax to use relative coordinates and not use , in between rather spaces

**Comment by wizjany** [comment]
1) worldedit has existed for years before mojang came up with their coordinate syntax. there is no "standard".
2) you can just do `//pos1` (and 2) and it will set that position to your current location. no need to even type in ~ ~ ~ or anything else. in the master branch (7.3 snapshots) you can even just use `//pos`.
3) using spaces instead of commas just leads to far more ambiguity, especially when commands can take multiple different sets of arguments. (e.g. `//somecmd [<pos>|<abc> <xyz>]` are ambiguous if <pos> were somehow two arguments instead of just one). it's also far less readable. (`//pos 1 2 3 4 5 6` vs `//pos 1,2,3 4,5,6` or `//pos 1,2 3,4 5,6` if we're doing 2d for some reason)

**Comment by Josh-65** [comment]
Ive only seen mods/plugins use ~ for the relative coodinate so that why I said standard. Didn't know not putting anything in would do it so thank for the info.

**Comment by mitchngwen** [comment]
//pos1 ~,0,~ this is very necessary for repetitive tasks. This just tells worldedit to use my current position plus the y level I just gave it instead of my current position y level. This way I do not have to fly up or dig down, I'll I have to do is walk around., assuming I know what Y level I need. :)
With this simple addition I can quickly select an area without flying to the exact location and having to type in the location I am already in or retyping commands.

Honestly I am surprised it is not added yet.

**Comment by mitchngwen** [comment]
BTW I am terrible at explaining things, so use your imagination, assuming you have one. lol!
