### ISSUE TITLE
Add author(s) to plugin.yml

### ISSUE THREAD

**Issue by isaaclepes** [EngineHub/WorldEdit#2196]
### The Problem

plugin.yml contains no authors, which is parsed by various version tracking utilities such as AutoPlug.

### A Solution

If the author's field contains at least 1 author, it will properly match the plugin to the spigot/bukkit resource.

For example, if I manually edit the plugin.yml to add this author's field, the plugin is properly detected by AutoPlug.

authors: [sk89q, me4502, LadyCailin, jbaero, DarkArc, octylFractal]

### Anything Else?

This was mentioned in issue https://github.com/EngineHub/WorldEdit/issues/108 title, but it appears the OP did not include any details and the conversation from then on was not applicable to this request.

**Comment by wizjany** [comment]
still unclear how this benefits anything. at best we'll put "enginehub" in the field, which isn't going to match anything on dbo (we don't release on spigot anyway). the only reason we'd add anything there is attribution which again, would go to the org because we don't want a list of 30 names (from your example, i would note that 2 of those people have never worked on worldedit, and another 2 haven't touched it in probably 8+ years. not sure where you even got that list). closing as a duplicate unless someone can come up with a compelling reason to list names there.

**Comment by isaaclepes** [comment]
I just got the list from the 'People' page of the Enginehub git.

Could it mention the spigot listed owner and then 'Enginehub Team'? 

Oh, you closed and rejected this.. never mind I guess I will just write a script to unpack the jar, edit the plugin file, and repack the jar when it changes versions.

**Comment by wizjany** [comment]
we literally do not have a spigot page. as far as i know spigot doesn't support org accounts either. i just went over this.

**Comment by isaaclepes** [comment]
Apologies, I meant Bukkit.org page.  It works with several providers, but you don't seem like you want to do anything here so I will leave you alone about it.  I have other ways to accomplish this, I was just trying to help the communities.
