### ISSUE TITLE
//gravitize

### ISSUE THREAD

**Issue by User3824** [EngineHub/WorldEdit#2366]
### The Problem

It's hard to make blocks gravity-affected.

### A Solution

Add a command that will make a selected region gravity affected.

### Alternatives

//cut and //paste: Might take too much effort for large regions

### Anything Else?

This command will toggle gravity for a region.

**Comment by me4502** [comment]
What exactly are you asking for here. Something that just applies block updates and causes blocks like sand to fall? If so `//update` already handles this. If you're asking for a command to make every block in an area into falling block entities, that's likely an extremely unsafe operation to do given the buggy nature and extreme performance implications of those entities

**Comment by User3824** [comment]
Well technically it's a command that will make all blocks fall in a region if they have void air, cave air or air below. The blocks will turn to notmal when they are finished falling.

**Comment by me4502** [comment]
So you're asking for one that creates falling block entities then. Due to the reasons I outlined in my last comment that doesn't sound like a good idea to do. The fact that they (normally) turn into normal blocks isn't the issue, it's that suddenly creating a large number of entities has awful performance, and they're extremely buggy in terms of whether they'll actually turn into normal blocks upon touching the ground or not. It's very possible due to some MC physics oddity they'll end up in the wrong places or never actually turn back into a block.

If you just want to raise/lower there are the raise & lower brushes.

**Comment by wizjany** [comment]
there's also just the gravity brush, which just skips the falling block entity and sets blocks down on the next solid surface below.

i agree that we don't want to mess with creating entities for this. at best, this could be a request for the gravity brush algorithm to be applied to a region instead of a brush.

**Comment by User3824** [comment]
Oh.
