### ISSUE TITLE
Chisels and Bits compatibility

### ISSUE THREAD

**Issue by Zockerhopper** [EngineHub/WorldEdit#2390]
### WorldEdit Version

7.2.14

### Platform Version

Fabric 0.14.21

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Whenever I try to //copy and //paste an area that includes a Block that I chiseled with Chisels and Bits that 'block' appears completely invisible (No Rendering) and when I break that 'block' it plays the Stone breaking sound, even when I used Wood.

### Expected Behavior

Well, that the Chiseled Block renders as it did in the copied area.

### Reproduction Steps

1. Launch Minecraft with Chisels and Bits - For Fabric and Worldedit
2. Launch a (Creative) World, use a Chisel on any Block, by just right clicking on it with the chisel, or use a Bit and place that anywhere.
3. Use the Axe and select a region with those Chiseled Blocks.
4. //copy and //paste it somewhere else and see how for some reason those blocks no longer render

### Anything Else?

Just for clarification Chisels and Bits 'blocks' all have the same ID (chiselsandbits:chiseledrock) but that can have different shapes depending on how you chisel away at a Block or build with the Chisels and Bits "Bits".

**Comment by cherbert** [comment]
for the love of god why in 2024 is this still not a feature!?

**Comment by me4502** [comment]
Because in general there's likely almost nothing we can actually do about it. Worldedit copies the data exactly as-is. If a mod stores data outside of the normal ways for MC to do it (which they shouldn't do), there's no way for worldedit to know about that data. 

Generally in cases like this, it's due to the mod doing something very weird with its blocks, and preventing them from being moved due to some weird external mapping directly with positions. If a mod wants to do something weird like that, they'd have to use our API to add support, but realistically they shouldn't be doing something weird in the first place
