### ISSUE TITLE
CraftBukkit 1.20.4 causes WorldEdit to say unsupported

### ISSUE THREAD

**Issue by mrjasonn** [EngineHub/WorldEdit#2448]
### WorldEdit Version

Bukkit-Official(7.2.18-SNAPSHOT+6611)

### Platform Version

CraftBukkit build 3969

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

It is saying that I am using unsupported Bukkit so I can't use some functions, I can't really find anything saying Craftbukkit not supported

### Expected Behavior

It should let me use as normal

### Reproduction Steps

1. Open a CraftBukkit 1.20.4 server with worldedit
2. Try using those edit functions which require supported versions

**Comment by me4502** [comment]
CraftBukkit in general isn't really supported by anyone anymore. It's not supported by its developers and isn't a build output artefact, it purely exists now as a preliminary build step of Spigot

Nothing is tested against it because it's not considered a platform that really exists anymore

**Comment by me4502** [comment]
My point was that CraftBukkit is not a published Bukkit platform, it’s a development artefact. If worldedit is working on Spigot, which is the only server software published by Spigot who maintain the Bukkit API, there’s no issue because it works on the reference implementation of Bukkit.

Spigot do not support nor recommend using CraftBukkit, it’s a build artefact. No plugins are tested against it because it’s not server software, it’s part of Spigot’s build pipeline.

**Comment by me4502** [comment]
The error occurs because worldedit couldn’t enable those functions
