### ISSUE TITLE
Deltree doesn't remove some floating trees

### ISSUE THREAD

**Issue by itsnotjasper** [EngineHub/WorldEdit#2451]
### WorldEdit Version

7.3.0-beta-02

### Platform Version

Bukkit

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Deltree doesn't remove trees that are floating but have grass/flowers under them.

### Expected Behavior

Trees deleted

### Reproduction Steps

1. Find a tree with grass alongside it 1 block above
2. Remove the bottom of the log
3. Attempt to delete the tree
![Example](https://github.com/EngineHub/WorldEdit/assets/43426628/b6dd71c4-f18f-4ff3-a728-2b11aa36d4bf)

**Comment by me4502** [comment]
I'm not really sure this can be considered a bug, or if it can be "entirely" solved. From the perspective of MC, that tree _isn't_ floating. Technically we could use a solid check, but that means trees on glass, full slabs, leaves, and a bunch of other blocks would be considered floating.

It's a fairly subjective thing here of what blocks makes a tree "float", and Minecraft has pretty strict definitions of these things that will have a lot of cases that don't match up with what you expect either way

**Comment by itsnotjasper** [comment]
I see. Would it be possible to perhaps add a /perf option to check for non-solids, or would that be difficult to implement?
Thank you

**Comment by wizjany** [comment]
1) this has nothing to do with perf

2) this is definitely not a bug.

3) i dont see any need for a change in behavior. the tool was originally designed to clean up after people who didnt fully chop down trees back in alpha/beta days because you couldnt reach the top block. i believe this really isnt the issue it used to be any more, and even if you need that functionality it's pretty trivial to left click the lowermost log and then right click the next one (something that also wasnt easy when this was designed, since creative mode didnt exist)
