### ISSUE TITLE
Incompatible with NeoForge 1.20.4 in Paper

### ISSUE THREAD

**Issue by qsef1256** [EngineHub/WorldEdit#2471]
### WorldEdit Version

7.2.19, 7.3.0 Beta 4

### Platform Version

git-Paper-426, NeoForge 20.4.161-beta

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Internal Exception: io.netty.handler.codec.DecoderException: Not enough bytes in buffer, expected 111, but got 12
![image](https://github.com/EngineHub/WorldEdit/assets/44014066/7c8b2deb-89e5-40be-baf6-d54f6e4f61c2)

### Expected Behavior

Can connect to a server with WorldEdit using NeoForge client.

### Reproduction Steps

1. Install WorldEdit to Paper server.
2. Install NeoForge and connect the server. (without any mods)

**Comment by me4502** [comment]
If a specific client mod (in this case NeoForge) causes the client to crash upon joining a server, it's that client mod that's causing the issue.

**Comment by qsef1256** [comment]
WorldEdit plugin is server-side. It should have nothing to do with what the client is. I can't connect to server with client optimization mods. If you still think it's a NeoForge issue, I'll open an issue on their issue tracker, but I think it's closer to a WorldEdit issue.

**Comment by me4502** [comment]
Yes, as you said worldedit is a server mod so it doesn't affect the client. WorldEdit isn't doing anything special here that could trigger an issue like this, everything it does goes through normal Minecraft channels. Given this only occurs with NeoForge, that indicates NeoForge has a bug that causes an error when completely normal data comes to the client.

This is most likely happening when Minecraft synchronises its internal list of commands, which is not something that plugins alter, they just register commands and Minecraft handles the rest. NeoForge likely has a bug in their packet reading code, it's not something that worldedit can fix in any way, because the issue isn't within worldedit

**Comment by qsef1256** [comment]
Okay, I found an issue that appears to be related to this problem. https://github.com/neoforged/NeoForge/issues/533, I'll close issue.
