### ISSUE TITLE
world edit 7.3.1 and 7.3.0 not working on craftbukkit 1.20.4

### ISSUE THREAD

**Issue by CharliVanNood** [EngineHub/WorldEdit#2501]
### WorldEdit Version

7.3.0

### Platform Version

CraftBukkit-1-20-4

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

after loading up the plugin and trying to make edits it gives me a warning the version of world edit doesn't support my version of bukkit, I've tried the newest snapshot 7.3.1 after but that one also doesn't work.

This WorldEdit version does not fully support your version of Bukkit. Block entities (e.g. chests) will be empty, block properties (e.g. rotation) will be missing, and other things may not work. Update WorldEdit to restore this functionality:
https://enginehub.org/worldedit/#downloads
Editing on unsupported versions is dissabled.

I'm already using the latest version of WorldEdit, also tried newest experimental version but nothing seems to work.

### Expected Behavior

I expected the plugin to support my version cause it is 1.20.4

### Reproduction Steps

1. install the latest version of bukkit
2. install worldedit 7.3.0 or 7.3.1

**Comment by me4502** [comment]
No one publishes CraftBukkit anymore, it’s not a platform that has existed outside of a development artefact for a long time.

we haven’t chosen to not support it, it’s just not a production jar that can properly run plugins because it’s not intended to be. You either got it from some sketchy site, a host that doesn’t understand this, or you’re using an interim build artefact you had to dig for. Don’t use CraftBukkit.

https://madelinemiller.dev/blog/stop-using-craftbukkit/
