### ISSUE TITLE
update on Forge

### ISSUE THREAD

**Issue by KorpsmansWrath** [EngineHub/WorldEdit#2569]
### The Problem

i really want to use this mod on 1.21 but im unable to because im running Forge and it hasnt been updated on Forge since 1.20.4 which wont work on 1.21

### A Solution

update the forge software part if you guys arent working on it please

### Anything Else?

![file](https://github.com/EngineHub/WorldEdit/assets/174852923/e1e684dc-3256-4eda-b4d6-b27ec7c47858)
the image to show

**Comment by me4502** [comment]
in general Forge is too broken of a platform to properly support, and we cannot distribute it in the same way as the other platforms due to incompatibilities it has with NeoForge. Supporting it for 1.20.4 was hard enough, as it caused significant tooling problems and was extremely difficult to test due to Forge itself breaking singleplayer worlds (with no mods installed).

**Comment by KorpsmansWrath** [comment]
oh alright so it would be better to get it all on neoforge?
