### ISSUE TITLE
.//repeat <number> command to repeat a chain of commands

### ISSUE THREAD

**Issue by MegaMinerDL** [EngineHub/WorldEdit#2677]
### The Problem

Sometimes I find I have to do a set of commands on repeat on a set of selections, for example I might do:

//stack 1 u -am stone
//shift 1 u
//rep stone dirt

//stack 1 u -am stone
//shift 1 u
//rep stone dirt

//stack 1 u -am stone
//shift 1 u
//rep stone dirt

(...)

### A Solution

Instead, a //repeat <number> command would repeat the last specified number of commands (ignoring non-slash messages), e.g.:

//stack 1 u -am stone
//shift 1 u
//rep stone dirt
//repeat 3

This would repeat the previous 3 commands in 1.

### Alternatives

Using up and enter keys to try speedrun the repetitive process.

**Comment by wizjany** [comment]
this goes into the category of "belongs in a macro mod, not worldedit" imo

**Comment by octylFractal** [comment]
I agree with that, I don't think we want to be tracking command history / working on a command history level for this type of thing. I could see it happening if we had more details in our operation level, so that we could easily replay an operation instead of re-parsing a command buffer (which may not even have the same effect when run like that, plus needs async handling for pastes and copies which would be very difficult). As it stands we don't have an operation history or details in it enough to make that, so I'm going to close this.
